# Generated by Django 3.0.4 on 2020-04-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=255)),
                ('light', models.TextField()),
                ('temp', models.TextField()),
                ('humidity', models.TextField()),
                ('watering', models.TextField()),
                ('fertilizer', models.TextField()),
                ('transplantatio', models.TextField()),
            ],
        ),
    ]
